Repository planetarium/Cocona.Docs, pull requests merged in 2023-08, with the labels that each got.

#5 Redesign document style
  Cocona.Docs/DocsBuilder.cs
  Cocona.Docs/DocumentCommand.cs
Labels: Medium

#6 ci: add nuget publish workflow
  .github/workflows/publish.yaml
  Cocona.Docs/Cocona.Docs.csproj
  scripts/determine-version.js
Labels: Medium

#7 Add sidebar
  Cocona.Docs/DocsBuilder.cs
  Cocona.Docs/DocumentCommand.cs
  samples/Cocona.Docs.Examples.Calc/CalculateCommand.cs
  samples/Cocona.Docs.Examples.Calc/Program.cs
Labels: Large

#10 make nullable and enum type more readable
  Cocona.Docs/DocumentCommand.cs
Labels: Extra Small
